services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-broker:9092
      KAFKA_CLUSTERS_0_PROPERTIES_security_protocol: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_sasl_mechanism: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_sasl_jaas_config: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      kafka:
        condition: service_healthy

  kafka-init:
    image: apache/kafka:4.1.1
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      sh -c '
        /opt/kafka/bin/kafka-topics.sh \
          --create --topic topic1 \
          --bootstrap-server kafka-broker:9092 \
          --command-config <(echo -e "security.protocol=SASL_PLAINTEXT\nsasl.mechanism=PLAIN\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";") \
          --partitions 1 --replication-factor 1 && \

        /opt/kafka/bin/kafka-topics.sh \
          --create --topic topic2 \
          --bootstrap-server kafka-broker:9092 \
          --command-config <(echo -e "security.protocol=SASL_PLAINTEXT\nsasl.mechanism=PLAIN\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";") \
          --partitions 1 --replication-factor 1
      '

  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka-broker
    container_name: kafka-broker
    expose:
      - 9092
    ports:
      - "9093:9093"
      - "9094:9094"
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:9092,EXTERNAL://localhost:9094
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

      # Enable SASL PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      # JAAS config for inter-broker communication (broker as client)
      KAFKA_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";

      # JAAS config for clients connecting to INTERNAL listener
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";

      # JAAS config for clients connecting to EXTERNAL listener
      KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: >-
        org.apache.kafka.common.security.plain.PlainLoginModule required
        user_${KAFKA_USERNAME}="${KAFKA_PASSWORD}";
    healthcheck:
      test: >
        bash -c 'echo -e "sasl.mechanism=PLAIN\nsecurity.protocol=SASL_PLAINTEXT\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";" > /tmp/client.properties && /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 --command-config /tmp/client.properties && rm -f /tmp/client.properties'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
