services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    env_file:
      - .env
      - .ui.env
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy

  kafka-init-topics:
    image: apache/kafka:4.1.1
    container_name: kafka-init-topics
    restart: "no"
    env_file:
      - .env
    volumes:
      # location of the topics' init script
      - ./init-topics.sh:/init-topics.sh:ro
    entrypoint: ["/bin/bash", "/init-topics.sh"]
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka-broker
    container_name: kafka-broker
    env_file:
      - .env
    expose:
      - $KAFKA_INTERNAL_PORT
    ports:
      - "9093:$KAFKA_CONTROLLER_PORT"
      - "9094:$KAFKA_EXTERNAL_PORT"
    healthcheck:
      test: >
        bash -c 'echo -e "sasl.mechanism=PLAIN\nsecurity.protocol=SASL_PLAINTEXT\nsasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";" > /tmp/client.properties && /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:${KAFKA_INTERNAL_PORT} --command-config /tmp/client.properties && rm -f /tmp/client.properties'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
