# How to run:
# docker compose -f compose.yml up -d

name: postgres
services:
  postgres-database:
    image: postgres:latest
    container_name: postgres-database
    restart: always
    env_file:
      - .env
    ports: # Expose the port to the outside of the Docker network
      - "5432:5432"
    expose: # Expose the port to other services in the Docker network
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # location of the databases' init script
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local